### ISSUE TITLE
As a player playing the game, I want to reinforce my territories with additional troops in the beginning of the round.

### ISSUE THREAD

**Issue by Cross55** [sopra-fs24-group-35/sopra-fs24-group-35-server#12]
- [ ] A player should be able to choose each territory and define how many troops he wants to reinforce.

- [ ] Therefore a player can click on a node that represents a territory on the map to choose each location and interact with it.

- [ ] A player should be able to tell how many troops he is able to reinforce.

**Comment by Cross55** [comment]
- [ ] Make territory selectable

**Comment by Cross55** [comment]
- [ ] Show how many troops are available to place

**Comment by Cross55** [comment]
- [ ] Show two buttons to increase and decrease the amount of troops to be deployed

**Comment by Cross55** [comment]
- [ ] Subtract the selected amount from the total available troops and add them to the territory

**Comment by SylverSezari** [comment]
- [ ] Add a function in GameController to get one territory back
