### ISSUE TITLE
As a player playing the game, I want to be able to attack nearby hostile territories with my troops.

### ISSUE THREAD

**Issue by Cross55** [sopra-fs24-group-35/sopra-fs24-group-35-server#13]
- [ ] A player should see how many troops are on each territory.

- [ ] A player should be able to interact with his territories and select an adjacent hostile territory. 

- [ ] The player should choose multiple times with how many troops he wants to attack with until you have only one troop left. 

- [ ] The player should have an input field to select with how many troops he wants to attack.

- [ ] The player should be able to go back from this selected territory and view the map normally.

- [ ] The player should have a button to press if he wants to attack with the specified troops.

- [ ] The math on how this fight goes should be automatically calculated and displayed.

**Comment by RPKosch** [comment]
- [ ] test

**Comment by Eposs111** [comment]
- [ ] Ensure the correct Troop amount is displaed on each territorie.

**Comment by Eposs111** [comment]
- [ ] Allow player to choose one of his fields to attack from and highlight it in some way.

**Comment by Eposs111** [comment]
- [ ] Indicate to the player the fields he can attack (adjacent)

**Comment by Eposs111** [comment]
- [ ] Ensure the player can attack multiple times in one turn.

**Comment by Eposs111** [comment]
- [ ] Make sure player cannot attack with only one troop left.

**Comment by Eposs111** [comment]
- [ ] Let player choose how many troops he wants to attack with.

**Comment by Eposs111** [comment]
- [ ] Add a possibility to choose how many troops a player want to attack with.

**Comment by Eposs111** [comment]
- [ ] Provide Button to confirm attack.

**Comment by Eposs111** [comment]
- [ ] Show outcome of battle automatically.

**Comment by Eposs111** [comment]
- [ ] Make sure Territory is implemented and works as planned (see class diagramm)

**Comment by Eposs111** [comment]
- [ ] Ensure attack function is implemented and works

**Comment by Eposs111** [comment]
- [ ] Ensure if territory is taken over. It registers it in the backend.

**Comment by SylverSezari** [comment]
- [ ] If territory is taken over, update in server how many troops player chooses to transfer to conquered territory
