### ISSUE TITLE
As a player, after finishing my attacks I want to be able to move my troops to a different field and fortify the troops on that field.

### ISSUE THREAD

**Issue by Cross55** [sopra-fs24-group-35/sopra-fs24-group-35-server#14]
- [ ] After combat a player must be able to select a territory on which he has more than one troop.
- [ ] A player must be able to move a choosable amount of those superfluous troops to a different territory he owns.
- [ ] A player must be restricted to only move his access troops to an adjacent territory.

**Comment by SylverSezari** [comment]
- [ ] Create a pop-up screen upon clicking on a territory. In it you should be able to at most choose all but one troop of this territory

**Comment by SylverSezari** [comment]
- [ ] After a click on a second territory, a method in the GameController should be called to transfer troops

**Comment by SylverSezari** [comment]
- [ ] Create a method in GameService to check if all territories between the two selected ones belong to the user
