### ISSUE TITLE
As a player when I conquer a territory from another player I want to obtain a Risk card.

### ISSUE THREAD

**Issue by Cross55** [sopra-fs24-group-35/sopra-fs24-group-35-server#15]
- [ ] After a player conquered a territory from another player. The victorious player obtains a Risk Card.

**Comment by SylverSezari** [comment]
- [ ] Create different risk cards in the client

**Comment by SylverSezari** [comment]
- [ ] Create card object in server

**Comment by SylverSezari** [comment]
- [ ] Add the action of getting a card after conquering a tile in the game controller
