### ISSUE TITLE
As a player if I have three Risk cards of the same kind, one of each kind or a combination of either with a joker, I want to be able to trade them for the specified troops.

### ISSUE THREAD

**Issue by Cross55** [sopra-fs24-group-35/sopra-fs24-group-35-server#16]
- [ ] A player is able to trade three Risk cards of the same kind or one of each kind or either combination with a joker card for the specified amount of troops. 
- [ ] The player must be able to assign those troops to a territory he owns.

**Comment by RPKosch** [comment]
- [ ] If the player clicks in the trade screen on a possible trade this trade gets executed and therefore the additional amount of troops gets added to the players overall troop count.

**Comment by RPKosch** [comment]
- [ ] If the trade button was clicked an addition window is opened where the possible trades are listed. The player can hover over the trades and click on each one.

**Comment by RPKosch** [comment]
- [ ] In the beginning of the turn there should be a button on the screen to click for trading. (Only visible if the player can trade -> if possible_trades funciton return != []

**Comment by RPKosch** [comment]
- [ ] Create a possible_trades function:
With that you should check if three of the same numbers or strings are in all_cards object. -> add to list the string if its possible
Check for three different numbers or strings in the all_card object -> add it to the possibilities
Check for either Combination with a joker and add it to the list.
Return list with possibilities

**Comment by RPKosch** [comment]
- [ ] Each Player has an object with all the cards. 
Cards should consist of a string and a number.
