### ISSUE TITLE
As a player if I captured all the territories of a continent I want to get the predetermined bonus to my troops every round.

### ISSUE THREAD

**Issue by Cross55** [sopra-fs24-group-35/sopra-fs24-group-35-server#17]
- [ ] If a player conquered all the territory in a continent the predetermined bonus he gets every round gets added automatically.
- [ ] If he loses a territory in this continent the bonus gets disabled automatically.

**Comment by Cross55** [comment]
- [ ] If a user

**Comment by Cross55** [comment]
- [ ] Test

**Comment by Cross55** [comment]
- [ ] Test

**Comment by Cross55** [comment]
- [ ] test

**Comment by roburkUZH** [comment]
- [] test

**Comment by RPKosch** [comment]
This is only a new test

**Comment by roburkUZH** [comment]
- [ ] test

**Comment by RPKosch** [comment]
- [ ] Make it possible to interact with the board. Game to Board interaction – Maybe Class creation of board?

**Comment by RPKosch** [comment]
- [ ] Make one function that check for bonuses for all the players (beginning of the game) (Gives back all the Players with the right bonuses)

**Comment by RPKosch** [comment]
- [ ] Make one function that check for bonuses for a specific player specific (for the one that is interacting currently with the game). (Gives back the right Players with the right bonuses)

**Comment by RPKosch** [comment]
- [ ] Make a dictionary in the board class where all the continents are listed as a key and then for the values a list that contain first a number for the bonus, and a list with all the corresponding territories (set owner to null).

**Comment by SylverSezari** [comment]
- [ ] Add Players to the Game  by getting them from the Lobby and creating Player entities
