### ISSUE TITLE
As a user I want an option to create and join game Lobbies.

### ISSUE THREAD

**Issue by Cross55** [sopra-fs24-group-35/sopra-fs24-group-35-server#2]
- [ ] In this screen you are able to create a Lobby so your friends can join and you can play together.
- [ ] When making a Lobby the standard name is: “[Username]’s game”.
- [ ] \(Optional) Offer an edit button with which you can edit the Lobby name.
- [ ] On the bottom add a button which redirects you to the game and starts the game.

**Comment by roburkUZH** [comment]
- [ ] Add a Create Lobby and a Join Lobby to the title screen.

**Comment by roburkUZH** [comment]
- [ ] On the title screen, once a player has clicked on the Join Lobby button, he should be able to enter the Lobby ID of the lobby he wants to join into a entry field and confirm. Implement that entry field and the confirm button.

**Comment by roburkUZH** [comment]
- [ ] Create a game lobby page including all GUI elements. The Lobby ID should be displayed somewhere on the screen.

**Comment by roburkUZH** [comment]
- [ ] Players who clicked on the Create Lobby button should be directly directed to the lobby screen and become the lobby owner. Using a POST request, the lobby should be created in the backend with one user (the lobby owner) in it. Don't forget to set the lobby owner in the lobby object representation.

**Comment by roburkUZH** [comment]
- [ ] If a lobby owner exits the lobby, the lobby should be deleted using a DELETE request.

**Comment by roburkUZH** [comment]
- [ ] Implement a Start Game button, which is only displayed on the client of the lobby owner. If not everybody in the lobby is ready yet, it should be grayed out and not clickable. If this button is clicked, the state of the lobby should change to "inGame" and the game should be started (also included in User Story 4).

**Comment by roburkUZH** [comment]
- [ ] Create a lobby class in the backend.

**Comment by roburkUZH** [comment]
- [ ] Create the REST controller for lobbies, the Lobby Service and the Lobby Repository including all the necessary methods according to the REST specification.
