### ISSUE TITLE
As a user I need a board on which I can play the game.

### ISSUE THREAD

**Issue by Cross55** [sopra-fs24-group-35/sopra-fs24-group-35-server#3]
- [ ] Create a board to play “Risk” on.
- [ ] Use the “standard” 42 fields formula.
- [ ] \(Optional) Create a new board map and add it to the selection.
- [ ] #106
- [ ] #107

**Comment by roburkUZH** [comment]
- [ ] test

**Comment by roburkUZH** [comment]
- [ ] This is an issue for test purposes.

**Comment by roburkUZH** [comment]
- [ ] test

**Comment by roburkUZH** [comment]
- [ ] Design the world map graphics. The graphics should be used as the background for the game board. Do not include any territory names, since they will appear on the buttons that will be distributed over the map (one button for one territory). But you may include edges that make it easier to spot which territories are next to each other (such that together with the buttons, which act as nodes, we get a graph representation of the territory map).

**Comment by roburkUZH** [comment]
- [ ] Design the territoy buttons. One button represents one territory. A territory button contains the name of a territory, the number of troops that are on that territory and should be of a certain color depending on the continent the territory belongs to. It should also show the owner of that territory. This could be done by displaying an example troop of a certain color depending on the player, or just by displaying the player name. The buttons should have some hover effect if a user moves his cursor over the buttons to give feedback that the buttons are clickable (Implementation of the function that is executed when the buttons are clicked is subject to User Story 13).

**Comment by roburkUZH** [comment]
- [ ] Create the game web page and include it to the react router. The game web page should display the world map graphics and the territory buttons. Also include GUI elements such as action buttons according to the specification.

**Comment by roburkUZH** [comment]
- [ ] Create a representation of the game object and its related objects in the frontend according to the specification. Using an useEffect() React hook, once the game web page is loaded, a new game should be created using a POST request to the server, but only on the frontend of the lobby owner. After that (maybe after some waiting time to give the server time to create the game), all the clients should perform a GET request to load the initial game data into the game object and its related objects.

**Comment by roburkUZH** [comment]
- [ ] If it's the player's turn to whom the client belongs to, make the territory buttons clickable (-> hover effect) and display GUI action buttons. Otherwise the territory buttons shouldn't be clickable and the GUI elements should be hidden.

**Comment by roburkUZH** [comment]
- [ ] For the board, an adjacency matrix should be implemented which keeps track on which territories are neighbouring. If multiple maps are implemented, every map should have its own adjacency matrix.

**Comment by roburkUZH** [comment]
- [ ] Create the game class and its related classes in the backend.

**Comment by roburkUZH** [comment]
- [ ] Create the game REST controller and include the POST request to create a game and the GET request such that the clients can fetch game data. Authentication should be done via a method from the User Service.

**Comment by roburkUZH** [comment]
- [ ] Include createGame() and getGame() in the Game Service file and create the game repository. The methods in the Game Service should be able to use the game repository (e.g. gameRepository.getById() etc.).

**Comment by roburkUZH** [comment]
- [ ] Implement code such that a game can be assigned to a lobby, such that a lobby "has" a game.

**Comment by SylverSezari** [comment]
- [ ] inititater TurnCycle at the beginning of a Game
