### ISSUE TITLE
As a logged-in user, once I am in the lobby, I want to check if everybody I want to play with is in the lobby and everybody is ready to start playing, such that the game can start.

### ISSUE THREAD

**Issue by Cross55** [sopra-fs24-group-35/sopra-fs24-group-35-server#4]
- [ ] A “ready” button is displayed in the lobby page, which is in “not ready” state by default.
- [ ] A user can show that he is ready for playing by clicking the “ready” button, such that it changes its state to “ready”.
- [ ] If a user has already clicked the “ready” button, but isn’t ready to play, he can click the “ready” button again, such that it changes its state to “not ready” again.
- [ ] In the list of players inside the lobby, the readiness state of every player should be displayed next to the username.
- [ ] Once the readiness state of every player is “ready”, the game starts automatically, but only if there are at least two players in the lobby.

**Comment by roburkUZH** [comment]
- [ ] Implement a Ready button, such that players can show if they're ready or not.

**Comment by roburkUZH** [comment]
- [ ] Implement a Start Game button, which is only displayed on the client of the lobby owner. If not everybody in the lobby is ready yet, it should be grayed out and not clickable. If this button is clicked, the state of the lobby should change to "inGame" and the game should be started.

**Comment by roburkUZH** [comment]
- [ ] On the clients of the users who don't own the lobby, once their ready button is activated, the client should repeatedly perform lobby GET requests and wait until the state of the lobby changes to "inGame". Then the game should be started.

**Comment by SylverSezari** [comment]
- [ ] Write test cases for lobby controller and service.
